# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 19:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='date_publication',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='espece',
            field=models.CharField(choices=[('CAT', 'Chat'), ('DOG', 'Chien')], default='CAT', max_length=3),
        ),
        migrations.AddField(
            model_name='animal',
            name='user_ajout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
