# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 16:56
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20170510_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='description2',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
