# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 12:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_animal_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image_temp',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='animal',
            name='apparence',
            field=models.CharField(max_length=200, verbose_name='Apparence'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout"),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_naissance',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_publication',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description texte'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description2',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description Tinymce'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='espece',
            field=models.CharField(choices=[('CAT', 'Chat'), ('DOG', 'Chien')], default='CAT', max_length=3, verbose_name='Espèce'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='location',
            field=models.CharField(max_length=30, verbose_name='Localisation actuelle'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='num_puce',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de puce'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='origine',
            field=models.CharField(max_length=200, verbose_name="Origine de l'animal"),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexe',
            field=models.CharField(choices=[('F', 'Femelle'), ('M', 'Male')], default='F', max_length=1, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='statut',
            field=models.CharField(choices=[('01', 'à adopter'), ('02', 'en attente'), ('03', 'adopté'), ('04', 'inactif')], default='01', max_length=2, verbose_name="Statut de l'animal"),
        ),
        migrations.AlterField(
            model_name='animal',
            name='taille',
            field=models.CharField(choices=[('S', 'Petit'), ('M', 'Moyen'), ('L', 'Grand'), ('XL', 'Très grand')], default='M', max_length=2, verbose_name='Taille'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='temperament',
            field=models.CharField(max_length=200, verbose_name='Tempérament'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='user_ajout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par'),
        ),
    ]
