# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_auto_20170512_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image_temp_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animal',
            name='image_temp_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image_temp',
            field=models.ImageField(blank=True, height_field='image_temp_height', null=True, upload_to='', width_field='image_temp_width'),
        ),
    ]
