# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import front.models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_auto_20170512_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image_temp',
            field=models.ImageField(blank=True, height_field='image_temp_height', null=True, upload_to=front.models.upload_location, width_field='image_temp_width'),
        ),
    ]
